### PR TITLE
Update translations for react-admin v3

### PR DESCRIPTION
**Pull request by m4theushw**
This PR fixes some translations and add new ones used in the upcoming react-admin v3. I took as a guide the english [file](https://github.com/marmelab/react-admin/blob/next/packages/ra-language-english/index.js).

I think it would be a good approach to create a `2.x.x` version of ra-language-portuguese to prevent breaking who is using the react-admin v2.

### CODE REVIEW

**Comment by marquesgabriel** [comment]
Looks good to me

**Comment by marquesgabriel** [comment]
gonna publish to npm soon

**Comment by marquesgabriel** [comment]
I'm so sorry for the delay. i've just published a new version on NPM:
[https://www.npmjs.com/package/ra-language-portuguese](https://www.npmjs.com/package/ra-language-portuguese)

**Comment by m4theushw** [comment]
No problem. I will add other translations soon.

**Comment by marquesgabriel** [comment]
@m4theushw I think i found you on LinkedIn. Can we talk?

**Comment by m4theushw** [comment]
Yes, sure!

**Pull request merged**
